name: Android APK (from zip)

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Unzip source
        run: |
          unzip -o cryptosage_ai_lite_source.zip -d tmp_src
          # Move all extracted files to root
          mv tmp_src/*/* . || mv tmp_src/* . 
          ls -la

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Flutter create scaffold
        run: |
          flutter --version
          flutter create .
          rm -rf lib pubspec.yaml
          cp -r app_src/lib ./lib
          cp app_src/pubspec.yaml ./pubspec.yaml

      - name: Get packages
        run: flutter pub get

      - name: Build APK (release)
        run: flutter build apk --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: cryptosage-ai-lite-apk
          path: build/app/outputs/flutter-apk/app-release.apk