name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Unzip source code
      run: |
        unzip cryptosage_ai_lite_source_v2.zip -d app

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x ./app/gradlew

    - name: Build APK
      run: cd app && ./gradlew assembleRelease

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: CryptoSageAI-Lite
        path: app/app/build/outputs/apk/release/*.apk
