name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Unzip source (v2)
        run: unzip -o cryptosage_ai_lite_source_v2.zip -d tmp_src

      - name: Find app_src
        run: |
          APP_SRC=$(find tmp_src -type d -name app_src | head -n 1)
          if [ -z "$APP_SRC" ]; then echo "app_src not found"; exit 1; fi
          echo "APP_SRC=$APP_SRC" >> $GITHUB_ENV

      - name: Setup Flutter (stable)
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Create Flutter project & copy sources
        run: |
          set -e
          flutter --version
          flutter create . --project-name cryptosage_lite --platforms=android
          rm -rf lib pubspec.yaml
          mkdir -p lib
          cp -a "$APP_SRC/lib/." ./lib/
          cp "$APP_SRC/pubspec.yaml" ./pubspec.yaml
          test -f lib/main.dart

      - name: Patch Flutter API change (CardTheme -> CardThemeData)
        run: |
          if grep -q '\bCardTheme\b' lib/theme.dart; then
            sed -i 's/\bCardTheme\b/CardThemeData/g' lib/theme.dart
            echo "Patched CardTheme -> CardThemeData"
          else
            echo "No CardTheme symbol found; skipping patch"
          fi

      - name: Set Android NDK version in Kotlin DSL
        run: |
          FILE=android/app/build.gradle.kts
          if [ -f "$FILE" ]; then
            sed -i '0,/android[[:space:]]*{/{s/android[[:space:]]*{/&\n    ndkVersion = "27.0.12077973"/}' "$FILE"
            echo "Applied ndkVersion to $FILE"
            grep -n 'ndkVersion' "$FILE" || (echo "ndkVersion not injected" && exit 1)
          else
            echo "$FILE missing" && exit 1
          fi

      - name: Get packages
        run: flutter pub get

      - name: Build APK (release)
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: cryptosage-ai-lite-apk
          path: build/app/outputs/flutter-apk/app-release.apk
